import { GlobalProvider } from '@/context/Provider'
import './globals.css'
import { Inter } from 'next/font/google'
import FramerLayout from '@/context/FramerLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <FramerLayout>
            {children}
          </FramerLayout>
        </GlobalProvider>
      </body>
    </html>
  )
}
